# Generated by Django 5.2.15 on 2026-07-07 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis', '0002_rubrica_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ESPERANDO_CONFIRMACION', 'Esperando confirmación'), ('CONFIRMADA', 'Confirmada'), ('EVALUANDO', 'Evaluando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], db_index=True, default='BORRADOR', max_length=30)),
                ('propuesta', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to=settings.AUTH_USER_MODEL)),
                ('rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='analisis.rubricaevaluacion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RECLUTADOR', 'Reclutador'), ('AGENTE', 'Agente')], max_length=20)),
                ('contenido', models.TextField()),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
