# Generated by Django 5.2.15 on 2026-07-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=20)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarea', to='vacantes.mensajevacante')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_conversacion', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
