# Generated by Django 5.2.15 on 2026-07-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_rubrica_inicial'),
        ('documentos', '0003_estados_analisis'),
        ('vacantes', '0002_tareaconversacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('PARCIAL', 'Parcial'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('completados', models.PositiveIntegerField(default=0)),
                ('sin_texto', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('SIN_TEXTO', 'Sin texto'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analisis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_vacante', to='analisis.analisisdocumento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_vacante', to='documentos.documento')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='vacantes.ejecucionvacante')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ejecucionvacante',
            constraint=models.UniqueConstraint(fields=('vacante', 'numero'), name='ejecucion_vacante_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionvacante',
            constraint=models.UniqueConstraint(fields=('ejecucion', 'documento'), name='evaluacion_ejecucion_documento_unica'),
        ),
    ]
