# Generated by Django 5.2.15 on 2026-07-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_origen_imap'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(db_index=True, default='WHATSAPP', max_length=20)),
                ('payload_sha256', models.CharField(max_length=64, unique=True)),
                ('objeto', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('IGNORADO', 'Ignorado'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], db_index=True, default='RECIBIDO', max_length=20)),
                ('payload_sanitizado', models.JSONField(blank=True, default=dict)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('recibido_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recibido_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente')], default='ENTRANTE', max_length=12)),
                ('tipo', models.CharField(db_index=True, max_length=30)),
                ('wa_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nombre_perfil', models.CharField(blank=True, max_length=255)),
                ('contenido_texto', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('timestamp_meta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('IGNORADO', 'Ignorado'), ('ERROR', 'Error')], db_index=True, default='RECIBIDO', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('recibido_at', models.DateTimeField(auto_now_add=True)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to='integraciones.eventowebhook')),
            ],
            options={
                'ordering': ['recibido_at', 'id'],
                'indexes': [models.Index(fields=['wa_id', 'recibido_at'], name='wa_msg_contacto_fecha')],
            },
        ),
    ]
